# Use an official Python runtime as a parent image
FROM python:latest

# Set the working directory to /app
WORKDIR /app/eva

# Copy the current directory contents into the container at /app
ADD *.tar /app/

CMD ['bash']
